# Generated by Django 5.2 on 2025-05-12 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='tranfer_time',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='id_transaction',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='id_notification',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='trans_content',
        ),
        migrations.AddField(
            model_name='transactions',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='my_app.accounts'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_to_account_set', to='my_app.accounts'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
