# Generated by Django 5.2 on 2025-05-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_tranfer_time_transactions_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participateform',
            name='donated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
