# Generated by Django 5.2 on 2025-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_users_created_score_alter_users_social_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
