# Generated by Django 5.2 on 2025-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_vote_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='donated_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_participants',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
